/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--bg-primary)',
        secondary: 'var(--bg-secondary)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'accent': 'var(--accent-color)',
        'accent-dark': 'var(--accent-dark)',
        'accent-light': 'var(--accent-light)',
        'border': 'var(--border-color)',
        'header': 'var(--header-bg)',
        'card': 'var(--card-bg)',
        'input': 'var(--input-bg)',
        'input-border': 'var(--input-border)',
        'danger': 'var(--danger-color)',
        'success': 'var(--success-color)',
        'warning': 'var(--warning-color)',
        'error': 'var(--danger-color)',
      },
      backgroundColor: {
        primary: 'var(--bg-primary)',
        secondary: 'var(--bg-secondary)',
        header: 'var(--header-bg)',
        card: 'var(--card-bg)',
        input: 'var(--input-bg)',
        accent: 'var(--accent-color)',
        'accent-dark': 'var(--accent-dark)',
        'accent-light': 'var(--accent-light)',
        danger: 'var(--danger-color)',
        success: 'var(--success-color)',
        warning: 'var(--warning-color)',
        error: 'var(--danger-color)',
      },
      textColor: {
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
        accent: 'var(--accent-color)',
        'accent-dark': 'var(--accent-dark)',
        'accent-light': 'var(--accent-light)',
        danger: 'var(--danger-color)',
        success: 'var(--success-color)',
        warning: 'var(--warning-color)',
        error: 'var(--danger-color)',
        white: '#ffffff',
      },
      borderColor: {
        primary: 'var(--border-color)',
        input: 'var(--input-border)',
        accent: 'var(--accent-color)',
        'accent-dark': 'var(--accent-dark)',
        'accent-light': 'var(--accent-light)',
        danger: 'var(--danger-color)',
        success: 'var(--success-color)',
        warning: 'var(--warning-color)',
        error: 'var(--danger-color)',
      },
      boxShadow: {
        theme: '0 1px 3px 0 var(--shadow-color), 0 1px 2px -1px var(--shadow-color)',
      },
      opacity: {
        '85': '0.85',
        '90': '0.90',
        '95': '0.95',
      },
    },
  },
  plugins: [],
  safelist: [
    'text-primary',
    'text-secondary',
    'text-accent',
    'text-accent-dark',
    'text-accent-light',
    'text-danger',
    'text-success',
    'text-warning',
    'text-error',
    'bg-primary',
    'bg-secondary',
    'bg-card',
    'bg-header',
    'bg-accent',
    'bg-accent-dark',
    'bg-accent-light',
    'bg-danger',
    'bg-success',
    'bg-warning',
    'bg-error',
    'border-primary',
    'border-accent',
    'border-accent-dark',
    'border-accent-light',
    'border-danger',
    'border-success',
    'border-warning',
    'border-error',
  ],
} 